<?php
/**
 * AgilityFieldType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Agility\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agility CMS REST API
 *
 * Agility CMS REST API for retrieving content from the Agility CMS.  The API Types are fetch (for published content) and preview (for latest, or staging content).
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.36
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Agility\Client\Model;
use \Agility\Client\ObjectSerializer;

/**
 * AgilityFieldType Class Doc Comment
 *
 * @category Class
 * @package  Agility\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgilityFieldType
{
    /**
     * Possible values of this enum
     */
    const TEXT = 'Text';
const NUMBER = 'Number';
const DECIMAL = 'Decimal';
const HTML = 'Html';
const HTMLUpper = 'HTML';
const LONG_TEXT = 'LongText';
const INTEGER = 'Integer';
const BOOLEAN = 'Boolean';
const DATE = 'Date';
const CONTENT = 'Content';
const LINK = 'Link';
const IMAGE_ATTACHMENT = 'ImageAttachment';
const PHOTO_GALLERY = 'PhotoGallery';
const CUSTOM_FIELD = 'CustomField';
const DROPDOWN_LIST = 'DropdownList';
const FILE_ATTACHMENT = 'FileAttachment';
const ATTACHMENT_LIST = 'AttachmentList';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TEXT,
self::NUMBER,
self::DECIMAL,
self::HTML,
self::HTMLUpper,
self::LONG_TEXT,
self::INTEGER,
self::BOOLEAN,
self::DATE,
self::CONTENT,
self::LINK,
self::IMAGE_ATTACHMENT,
self::PHOTO_GALLERY,
self::CUSTOM_FIELD,
self::DROPDOWN_LIST,
self::FILE_ATTACHMENT,
self::ATTACHMENT_LIST,        ];
    }
}
